# This file is meant for internal use only. It lists folders
# and files that should be excluded from OSS scan.

excludes:
  scopes:
  - name: "debug.*"
    reason: "TEST_TOOL_OF"
    comment: "Scope with dependencies only used for testing. Not included in built examples."
  - name: "lintClassPath"
    reason: "TEST_TOOL_OF"
    comment: "Scope with dependencies only used for testing. Not included in built examples."
  - name: "test.*"
    reason: "TEST_TOOL_OF"
    comment: "Scope with dependencies only used for testing. Not included in built examples."
  - name: ".*Test.*"
    reason: "TEST_TOOL_OF"
    comment: "Scope with dependencies only used for testing. Not included in built examples."
